let handler = async (m, { conn }) => await conn.sendBL(m.chat, `
${pickRandom(global.pantun)}
`.trim(), wm, fla + 'pantun', [['Pantun', '.pantun']], m)

handler.help = ['pantun']
handler.tags = ['quotes']
handler.command = /^(pantun)$/i

module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

global.pantun = [
" *PANTUN:*\n\nJalan² ke malaysia\nTak lupa beli pita\nJangan baca pantun saya\nNanti bisa jatuh cinta\n\n by instagram.com/rasel.ganz <3",
" *PANTUN:*\n\nSatu titik\nDua koma\nKamu cantik\nAku yang punya",
" *REQUEST:*\n\nPunya pantun sendiri? mau dimasukin ke list pantun bot? hubungi *.owner*\nwa.me/6285346545126",
" *PANTUN:*\n\nWaktu daftar hari terakhir\nwaktu terasa banyak terbuang\nKamu nggak perlu khawatir\ncintaku hanya untukmu seorang",
" *PANTUN:*\n\nApi kecil dari tungku\napinya kecil habis kayu\nSudah lama kutunggu-tunggu\nkapan kamu bilang I love you",
" *PANTUN:*\n\nAyam goreng setengah mateng\nbelinya di depan tugu\nAbang sayang, abangku ganteng\nNeng di sini setia menunggu",
" *PANTUN:*\n\nJalanan lagi lancar\nitu adalah sebuah berkah\nAku bukan nyari pacar\ntapi nyari yang mau diajak nikah",
" *PANTUN:*\n\nMinum sekoteng hangat rasanya\nminum segelas ada yang minta\nLaki-laki ganteng siapa yang punya?\nBolehkah aku jatuh cinta",
" *PANTUN:*\n\nBagaimana memanjat pohon randu?\nTangan di atas kaki ke hulu\nBagaimana hati tak rindu?\nPacarnya lembut suka melucu",
" *PANTUN:*\n\nPaling banyak burung gelatik\ndi atas terbang melayang\nMemang banyak wanita cantik\ncuma engkau yang aku sayang",
" *PANTUN:*\n\nSeribu bebek di kandang singa\nhanya satu berwarna belang\nBeribu cewek di Indonesia\nhanya engkau yang aku sayang",
" *PANTUN:*\n\nBawa paku dipukul batu\ndicampur jamu di atas tungku\nCintaku cukuplah satu\nuntuk kamu sepanjang waktu",
" *PANTUN:*\n\nAir mawar di dalam cangkir\ndisimpan kendi di bawah parang\nSedari awal hinggalah akhir\nsayangku tercurah untukmu seorang",
" *PANTUN:*\n\nSapu rumah hingga bersih\natapnya satu dibawa pergi\nTatap mataku wahai kekasih\ncintaku satu tak terbagi-bagi",
" *PANTUN:*\n\nDaging ayam dibuat gulai\nbuat dimakan kita nanti\nDirimu seorang yang ternilai\ntakkan pernah bisa diganti",
" *PANTUN:*\n\nTak usah menggurui\ndia itu kepala suku\nPerlu kamu ketahui\nkamu adalah semangat hidupku",
" *PANTUN:*\n\nAir arak diharamkan\nkarenanya banyak nyawa melayang\nMeskipun jarak memisahkan\nsemua itu bukan penghalang",
" *PANTUN:*\n\nJalan – jalan ke Kota Ratu\nbeli roti berisi bulu\nMari cantik kita bersatu\nmenjalin cinta di depan penghulu",
" *PANTUN:*\n\nLangit biru terlihat sendu\nwarna hijau biru dan semu\nJarak jauh tumbuhkan rindu\ningin selalu dekat denganmu",
" *PANTUN:*\n\nBerlabuh orang menunggu\nhendak berlayar ke Siantar\nKalau jauh terasa rindu\njika berjumpa terasa sebentar",
" *PANTUN:*\n\nPatah dahan disambungkan\nhendak hati disatukan\nKepada Tuhan kita mohonkan\nagar cepat dipertemukan",
" *PANTUN:*\n\nMeski hanya sebuah jambu\ntetap bisa dibuat jamu\nMeski jarang kita bertemu\ncintaku tetap hanya untukmu",
" *PANTUN:*\n\nJikalau ikan di dalam kolam\nbunganya tumbuh di tengah taman\nJikalau cintaku sudah mendalam\njaraknya jauh tak ku hiraukan",
" *PANTUN:*\n\nWahai seruling buluh perindu\nsuaranya memikatku\nWahai gadis pujaanku\naku sangat cinta kamu",
" *PANTUN:*\n\nNunggu angkot di belokan\nNaik angkot bertemu kamu\nIngin segera ku ungkapkan\nRasa cinta ini kepadamu",  
" *PANTUN:*\n\nDi semak ada kemumu\nHinggap di daun bunganya biru\nHai adek berjilbab biru\nHati tergerak ingin tahu namamu",
" *PANTUN:*\n\nJangan pegang duri Mawar\nDurinya sungguh tajam sekali\nMelihat adik rindu tertawar\nSiapakah namamu si pelita hati?",
" *PANTUN:*\n\nKupu-kupu hinggap di alis\nLetakkan kepala di atas bantal\nUntuk kamu pemilik senyum manis\nTak tertahan lagi ingin mengenal",
" *PANTUN:*\n\nAda ayam ada itik\nBerjalan sambil mengangguk-angguk\nSelamat malam wanita cantik\nKenalan yuuk",
" *PANTUN:*\n\nPergi ke kebun memanen kacang\nJalan ke kebun lewati aspal\nPemilik rambut terurai panjang\nBolehkan kita saling kenal?",
" *PANTUN:*\n\nBunga kembang jangan dipetik\nNanti tak lagi indah menawan\nUntuk kamu yang berwajah cantik\nBolehkah kita berkenalan?",
" *PANTUN:*\n\nSebelum Adzan Tabuh di pukul\nMarilah shalat perbanyak amal\nUntuk kamu bergigi gingsul\nHati bergejolak ingin mengenal",
" *PANTUN:*\n\nMakan nasi ditemani bakwan\nMinumnya dengan air susu\nWahai nona cantik rupawan\nBolehkan aku tahu namamu?", 
" *PANTUN:*\n\nDi Jam Gadang banyak Badut\nMembuat anak-anak jadi gembira\nPria mana yang tak terpincut\nIngin kenal denganmu sang jelita",
" *PANTUN:*\n\nJilbab putih dan abu-abu\nDipakai dengan indahnya gamis\nBolehkah ku tahu namamu\nUntuk kamu yang senyumnya manis",
" *PANTUN:*\n\nJalan-jalan ke Ciamis\nJangan lupa membeli Rambutan\nUntuk adinda yang berwajah manis\nBolehkah abang kenalan?",
" *PANTUN:*\n\nAceh terkenal si Bungong Jeumpa\nDijadikan pengiring Tari Saman\nAdik cantik siapa yang punya\nBolehkan kita untuk berkenalan?",
" *PANTUN:*\n\nPeganglah kayu yang tak rapuh\nAgar sampai engkau ke tuju\nSebelum adik pergi menjauh\nLebih baik kita berkenalan dulu",
" *PANTUN:*\n\nJalan ke medan berliku-liku\nTapi tidak ada begal\nNasib ke depan tak ada yang tahu\nAlangkah baiknya kita saling mengenal",
" *PANTUN:*\n\nPergi ke sungai mandikan gajah\nGajah bersih di hari petang minggu\nAduhai manisnya kamu punya wajah\nBolehkan abang mengenal dirimu?", 
" *PANTUN:*\n\nRendah terbangnya si kupu-kupu\nHinggap tenang di tali jemuran\nHati tergerak mulut malu\nKarena ingin sekali berkenalan",  
" *PANTUN:*\n\nKalau Kamu jago lukis\ncoba lukis ikan hiu\nKalau Kamu jago Bahasa Inggris\ncoba tulis i love you untukku", 
" *PANTUN:*\n\nJauh-jauh ke Negeri Cina\nhanya untuk mencari ilmu\nNamamu saja sudah sangat mempesona\napalagi dengan senyummu", 
" *PANTUN:*\n\nBeli kain warnanya merah\ndari kediri pakainya batik\ndigodain jangan marah\nsalah sendiri punya wajah cantik", 
" *PANTUN:*\n\nNaik sepeda jalan ke kota\njangan lupa memakai topinya\nMaksud hati ingin berkata\nbiarlah tulisan ini menjadi wakilnya", 
" *PANTUN:*\n\nJuragan pisau makan buah\neh buah kotor terkena tinta\njanganlah resah dan jangan gundah\nkarena rindu ini bumbu cinta", 
" *PANTUN:*\n\nNaik kereta mereknya Honda\npergi selayang ke tempat hadapi\nBila cinta mekar di dada\nsiang malam terbawa mimpi", 
" *PANTUN:*\n\nBurung dara dimakan hama\nburung dara makan jamu\nAku rela dipenjara lama\nasalkan penjara itu di hatimu", 
" *PANTUN:*\n\nBawa rantang isinya nasi\nnasi dimakan dibagi rata\nBiarlah bintang yang menjadi saksi\nuntuk mengawali cinta kita", 
" *PANTUN:*\n\nMengapa ada telaga\nkarena air yang mengisi\nMengapa ada cinta\njika dirimu tak dapat kumiliki", 
" *PANTUN:*\n\nAir hangat air soda\ntaruh dibangku buang sekali\nkehadiranmu sungguh menggoda\nmembuat hati semangat kembali", 
" *PANTUN:*\n\nBawa paku dipukul batu\ndicampur jamu di atas tungku\nberibu wanita yang mencariku\nhanya Kamu yang aku tunggu", 
" *PANTUN:*\n\nBeli buku isinya tebal\nhabis itu membeli buku\nIni serius loh bukan gombal\nmau nggak jadi pacarku", 
" *PANTUN:*\n\nRajin olahraga bikin tubuh sehat\njangan lupa sarapan dulu\nbangun pagi sungguh semangat\nkalau ingat senyum manismu", 
" *PANTUN:*\n\nBuah salak buah delima\nAda banyak wanita cantik hanya Kamu yang aku cinta", 
" *PANTUN:*\n\nAda burung gagak dan penyu\nKamu tau nggak aku rindu pengen ketemu", 
" *PANTUN:*\n\nTante cantik jualan jamu\njamu diminum rasa mengkudu\nMeski kita jarang bertemu\ncintaku hanyalah untukmu", 
" *PANTUN:*\n\nKamu Prancis aku Belgia\nKamu yang manis siapa yang punya", 
" *PANTUN:*\n\nUndur undur nabrak tukang jamu\naku gak bisa tidur nih mikirin Kamu", 
" *PANTUN:*\n\nIkan nila berenang di kolam\nair kolam amatlah dalam\nDari lubuk hati terdalam\nkuucapkan selamat malam", 
" *PANTUN:*\n\nMakan soto di Surabaya\nkalau jomblo boleh kenalan nggak ya", 
" *PANTUN:*\n\nSabtu pagi beli pasta gigi\nlalu siangnya beli kacamata\nHey Kamu, selamat pagi\niya Kamu yang aku cinta",  
" *PANTUN:*\n\nHobiku itu menyelam\nketika menyelam pasti aku mengajak teman minimal satu\nAku ingin sekali kamu tenggelam\ntenggelam di dalam hatiku",
" *PANTUN:*\n\nOrang itu bukanlah hantu\ntapi orang itu adalah tamu\nAku ingin menjadi kunci pintu\nsupaya aku dapat membuka pintu hatimu",
" *PANTUN:*\n\nBarang itu adalah barang yang antik\ntadi penjual barang antik tersebut datang kesini bertamu\nBerjuta-juta wanita yang cantik\ntiada wanita cantik selain dirimu",
" *PANTUN:*\n\nLaki-laki itu bukan saya\ntetapi itu adalah sahabatku\nBapak kamu seorang pencuri ya\nsoalnya kau telah mencuri hatiku",
" *PANTUN:*\n\nAku itu sulit dalam menghafal\nsoalnya aku males baca buku\nKau bagaikan sebuah kapal\nyang berlabuh di hatiku",
" *PANTUN:*\n\nBuat sangkar harus pakai paku\nsebelum buat sangkar enaknya minum jamu\nTidak ada wanita lain di hatiku\nkarena hatiku hanya untukmu",  
" *PANTUN:*\n\nMakanan busuk memang bau\nbila dimakan rasanya pahit seperti jamu\nSebenarnya ku ingin kau tau\naku tak bisa hidup tanpa cintamu",
" *PANTUN:*\n\nNaruh uang di dalam saku\nsakunya sobek gara-gara kena kuku\nangan sampai kau mengkhianatiku\nkarena hanya dirimu yang ada di hatiku",
" *PANTUN:*\n\nPunya istri cuma satu\nmalah seorang penjual jamu\nAku ingin ungkapkan sesuatu\nyaitu aku ingin mendapatkan cinta yang tulus darimu",
" *PANTUN:*\n\nMakan ayam lalapannya kemangi\ntetapi jangan lupa bersihin kuku\nTak ada wanita lain yang aku sayangi\nhanya kamulah wanita yang mengisi hatiku",
" *PANTUN:*\n\nIbu-ibu sukanya ngebatik\nkalau bapak-bapak sukanya rebana\nkau wanita yang paling cantik\nyang dapat membuatku terpana",
" *PANTUN:*\n\nKau seperti sekuter matic\nyang sering dinaiki si Nita\nBagiku kau wanita cantik\nyang dapat membuat semua laki-laki jatuh cinta", 
" *PANTUN:*\n\nUdah bikin janji malah lupa\ntapi aku tidak akan lupa dengan cita-cita\nAku memang tidak bisa memberimu apa-apa\nkarena yang bisa ku beri hanya kasih sayang dan cinta",
" *PANTUN:*\n\nKu ajak pergi ke pantai kau tidak mau\nsoalnya aku ingin berdua denganmu\nSaat ini yang perlu kau tau\nku tak bisa hidup tanpa dirimu",  
" *PANTUN:*\n\nBuah salak buah duku\ntidak bisa dibuat jamu\nBila kau belah dadaku\nakan kau temukan tulisan namamu", 
" *PANTUN:*\n\nPagi-pagi enaknya makan roti\nkarena setelah itu harus pergi menuntut ilmu\nKamu jangan berkecil hati\nkarena hatiku hanya untukmu",
" *PANTUN:*\n\nCinta itu bermula dari mata\ndan terkadang tertulis sampai ke buku\nKau bagaikan nelayan cinta\nyang selalu menebar benih-benih cinta di hatiku", 
" *PANTUN:*\n\nLihat Messi mencetak gol\ntiba-tiba datang seorang tamu\nAku ingin menjadi borgol\nsupaya dapat memborgol cintamu",
" *PANTUN:*\n\nPunya istri cuma satu\ndia malah seorang penjual jamu\nAku ingin ungkapkan sesuatu\naitu aku ingin mendapatkan cinta yang tulus darimu", 
" *PANTUN:*\n\nKemarin aku habis dilempar batu\nternyata yang nglembar batu itu ikan hiu\nSebenarnya aku ingin katakan sesuatu\nyaitu I love you",
" *PANTUN:*\n\nKu ajak pergi ke pantai kau tidak mau\nsoalnya aku ingin berdua denganmu\nSaat ini yang perlu kau tau\nku tak bisa hidup tanpa dirimu",
" *PANTUN:*\n\nAda wanita yang rambutnya sebahu\nternyata dia seorang penjual jamu\nHari ini kau harus tahu\naku tak bisa hidup tanpa cintamu", 
" *PANTUN:*\n\nKalau nembak cewek jangan pakai senapan\nberilah dia buah duren\nAku memang bukan orang yang tampan\ntetapi aku imut-imut dan keren", 
" *PANTUN:*\n\nLihat Messi mencetak gol\ntiba-tiba datang seorang tamu\nAku ingin menjadi borgol\nsupaya dapat memborgol cintamu", 
" *PANTUN:*\n\nBarang itu adalah barang yang antik\ntadi penjual barang antik tersebut datang kesini bertamu\nBerjuta-juta wanita yang cantik\ntiada wanita cantik selain dirimu",
" *PANTUN:*\n\nAda wanita yang rambutnya sebahu\nternyata dia seorang penjual jamu\nHari ini kau harus tahu\naku tak bisa hidup tanpa cintamu",
" *PANTUN:*\n\nLaki-laki itu bukan saya\ntetapi itu adalah sahabatku\nBapak kamu seorang pencuri ya\nsoalnya kau telah mencuri hatiku",
" *PANTUN:*\n\nAku itu sulit dalam menghafal\nsoalnya aku males baca buku\nKau bagaikan sebuah kapal\nyang berlabuh di hatiku",
" *PANTUN:*\n\nOrang itu bukanlah hantu\ntapi orang itu adalah tamu\nAku ingin menjadi kunci pintu\nsupaya aku dapat membuka pintu hatimu ", 
" *PANTUN:*\n\nPunya istri cuma satu\ndia malah seorang penjual jamu\nAku ingin ungkapkan sesuatu\nyaitu aku ingin mendapatkan cinta yang tulus darimu",
" *PANTUN:*\n\nHobiku itu menyelam\nketika menyelam pasti aku mengajak teman minimal satu\nAku ingin sekali kamu tenggelam\ntenggelam di dalam hatiku",  
" *PANTUN:*\n\nCinta itu bermula dari mata\ndan terkadang tertulis sampai ke buku\nKau bagaikan nelayan cinta\nyang selalu menebar benih-benih cinta di hatiku",
" *PANTUN:*\n\nNaruh uang di dalam saku\nsakunya sobek gara-gara kena kuku\nJangan sampai kau mengkhianatiku\nkarena hanya dirimu yang ada di hatiku",
" *PANTUN:*\n\nKu ajak pergi ke pantai kau tidak mau\nsoalnya aku ingin berdua denganmu\nSaat ini yang perlu kau tau\nku tak bisa hidup tanpa dirimu",  
" *PANTUN:*\n\nMakan ayam lalapannya kemangi\ntetapi jangan lupa bersihin kuku\nTak ada wanita lain yang aku sayangi\nhanya kamulah wanita yang mengisi hatiku",
" *PANTUN:*\n\nUdah bikin janji malah lupa\ntapi aku tidak akan lupa dengan cita-cita\nAku memang tidak bisa memberimu apa-apa\nkarena yang bisa ku beri hanya kasih sayang dan cinta",
" *PANTUN:*\n\nKemarin aku habis dilempar batu\nternyata yang nglembar batu itu ikan hiu\nSebenarnya aku ingin katakan sesuatu\nyaitu I love you",
" *PANTUN:*\n\nPunya istri cuma satu\ndia malah seorang penjual jamu\nAku ingin ungkapkan sesuatu\nyaitu aku ingin mendapatkan cinta yang tulus darimu",
" *PANTUN:*\n\nIbu-ibu sukanya ngebatik\nkalau bapak-bapak sukanya rebana\nkau wanita yang paling cantik\nyang dapat membuatku terpana",
" *PANTUN:*\n\nKau seperti sekuter matic\nyang sering dinaiki si Nita\nBagiku kau wanita cantik\nyang dapat membuat semua laki-laki jatuh cinta", 
" *PANTUN:*\n\nKu ajak pergi ke pantai kau tidak mau\nsoalnya aku ingin berdua denganmu\nSaat ini yang perlu kau tau\nku tak bisa hidup tanpa dirimu",
" *PANTUN:*\n\nPagi-pagi enaknya makan roti\nkarena setelah itu harus pergi menuntut ilmu \nKamu jangan berkecil hati\nkarena hatiku hanya untukmu",
" *PANTUN:*\n\nKalau nembak cewek jangan pakai senapan\nberilah dia buah duren\nAku memang bukan orang yang tampan\ntetapi aku imut-imut dan keren",
" *PANTUN:*\n\nBuat sangkar harus pakai paku\nsebelum buat sangkar enaknya minum jamu\nTidak ada wanita lain di hatiku\nkarena hatiku hanya untukmu",
" *PANTUN:*\n\nMakanan busuk memang bau\nbila dimakan rasanya pahit seperti jamu\nSebenarnya ku ingin kau tau\naku tak bisa hidup tanpa cintamu",
" *PANTUN:*\n\nBuah salak buah duku\ntidak bisa dibuat jamu\nBila kau belah dadaku\nakan kau temukan tulisan namamu",
" *PANTUN:*\n\nNaik motor sama mama papa\npakainya motor matik\nEeee tadi aku pikir siapa\nTernyata adinda yang cantik",
" *PANTUN:*\n\nGula pasir lebih manis gula jawa\nbuah mahoni lebih pahit dari jamu\nHatiku ini takkan mendua\nkarena hati ini telah jadi milikmu",
" *PANTUN:*\n\nJalan-jalan ke negara Inggris\nbanyak gedung berbaris-baris\nAku rela ditusuk ditusuk keris\ndemi cintakmu kepada Adinda yang manis", 
" *PANTUN:*\n\nKau bagaikan sebuah jalan\nyaitu sebuah jalan yang berliku-liku\nBagiku kau adalah rembulan\nyang bersinar terang menyinari hidupku",
" *PANTUN:*\n\nJalan-jalan ke negara Inggris\nbanyak gedung berbaris-baris\nAku rela ditusuk ditusuk keris\ndemi cintakmu kepada Adinda yang manis",
" *PANTUN:*\n\nKau seperti sekuter matic\nyang sering dinaiki si Nita\nBagiku kau wanita cantik\nyang dapat membuat semua laki-laki jatuh cinta",   
" *PANTUN:*\n\nKau bagaikan sebuah jari-jari\nyang memegang erat sebuah paku\nKau sama seperti pencuri\nyang telah mencuri hatiku", 
" *PANTUN:*\n\nBunga itu bunga mawar\nsering ditaruh sebagai hiasan saku\nAku ingin menjadi trotoar\nsupaya kau dapat berjalan dengan mudah ke hatiku",
" *PANTUN:*\n\nAir itu suka diobaok-obok\nhabis diobok-obok terus diminumkan ke sapi\nHabis mandi langsung bobok\nsupaya bisa cepet ketemu kamu di dalam mimpi",
" *PANTUN:*\n\nIbu-ibu sukanya ngebatik\nkalau bapak-bapak sukanya rebana\nkau wanita yang paling cantik\nyang dapat membuatku terpana",
" *PANTUN:*\n\nManusia dibagi menjadi dua jenis\nserta ada yang muda dan ada yang tua\nKau hari ini tambak begitu manis\nsampai-sampai melebihi manisnya Gita Gutawa",
" *PANTUN:*\n\nTubuhmu begitu lentik\npasti kamu sering minum jamu\nBagi orang lain mungkin kau tidak terlalu cantik\ntapi bagiku tidak ada yang secantik dirimu", 
" *PANTUN:*\n\nBagiku kau itu setangkai kembang\nkembang yang tak akan pernah jemu\nAku ingin menjadi kumbang\nsupaya bisa sering hinggap di pelukmu",
" *PANTUN:*\n\nKemarin aku habis dilempar batu\nternyata yang nglembar batu itu ikan hiu\nSebenarnya aku ingin katakan sesuatu\nyaitu I love you",
" *PANTUN:*\n\nMakanan busuk memang bau\nbila dimakan rasanya pahit seperti jamu\nSebenarnya ku ingin kau tau\naku tak bisa hidup tanpa cintamu",
" *PANTUN:*\n\nBuah salak buah duku\ntidak bisa dibuat jamu\nBila kau belah dadaku\nakan kau temukan tulisan namamu",
" *PANTUN:*\n\nJalan-jalan pakai motor matik\nsambil bawa bekal telur dadar\nKau hari ini tampak begitu cantik\nsampai melebihi Jesika Iskandar",
" *PANTUN:*\n\nMakan nasi sama sekoteng\nminumnya minum jamu\nAku memang bukan orang ganteng\ntapi hatiku ini tulus untukmu", 
" *PANTUN:*\n\nNaik motor sama mama papa\npakainya motor matik\nEeee tadi aku pikir siapa\nTernyata adinda yang cantik", 
" *PANTUN:*\n\nGula pasir lebih manis gula jawa\nbuah mahoni lebih pahit dari jamu \nHatiku ini takkan mendua\nkarena hati ini telah jadi milikmu", 
]
